
# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          choco install haxe --version 4.2.5 -y
          RefreshEnv
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 8.0.2
          RefreshEnv
          haxelib install openfl 9.3.3
          haxelib install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-addons 3.2.2
          haxelib install flixel-ui 2.6.1
          haxelib install newgrounds
          haxelib install hscript
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixelTextureAtlas https://github.com/Smokey555/Flixel-TextureAtlas.git
          haxelib git fnf-modcharting-tools https://github.com/TheZoroForce240/FNF-Modcharting-Tools
          haxelib install hxcpp-debug-server
          haxelib install hxcpp
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git polymod https://github.com/larsiusprime/polymod.git f3c0320aa51c848318934c2893ed78f42b7de74c
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install actuate 
          haxelib list
      - name: Compile
        run: |
          haxelib run lime build windows
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: export/release/windows/bin
